// <auto-generated> — do NOT edit by hand.
// Generated from src/Bevel.Themes.Win2000/theme.json by tools/ThemeGen (MET-01 / bevel-51t).
// Edit theme.json and run `dotnet run --project tools/ThemeGen`; CI fails on drift.

namespace Bevel.UI;

/// <summary>
/// The semantic theme-token keys (bevel-38y) — the contract between Bevel-owned controls and
/// whichever theme is active (Win2000 default; Luna/Win11 later). Values live in the theme
/// (generated Tokens.axaml for Win2000, per docs/spec/05-theming.md §3/§5/§8.1); controls bind
/// these keys via DynamicResource in AXAML or resource lookup in code-behind and never
/// hardcode palette hex or metric values. ThemeTokenTests keeps keys and theme in lockstep.
/// </summary>
public static class ThemeTokens
{
    public const string ColorButtonFace = "Bevel.Color.ButtonFace";
    public const string ColorButtonHighlight = "Bevel.Color.ButtonHighlight";
    public const string ColorButtonLight = "Bevel.Color.ButtonLight";
    public const string ColorButtonShadow = "Bevel.Color.ButtonShadow";
    public const string ColorButtonDkShadow = "Bevel.Color.ButtonDkShadow";
    public const string ColorWindow = "Bevel.Color.Window";
    public const string ColorWindowText = "Bevel.Color.WindowText";
    public const string ColorWindowFrame = "Bevel.Color.WindowFrame";
    public const string ColorGrayText = "Bevel.Color.GrayText";
    public const string ColorAppWorkspace = "Bevel.Color.AppWorkspace";
    public const string ColorDesktop = "Bevel.Color.Desktop";
    public const string ColorMenu = "Bevel.Color.Menu";
    public const string ColorMenuText = "Bevel.Color.MenuText";
    public const string ColorScrollbar = "Bevel.Color.Scrollbar";
    public const string ColorActiveTitle = "Bevel.Color.ActiveTitle";
    public const string ColorGradientActiveTitle = "Bevel.Color.GradientActiveTitle";
    public const string ColorInactiveTitle = "Bevel.Color.InactiveTitle";
    public const string ColorGradientInactiveTitle = "Bevel.Color.GradientInactiveTitle";
    public const string ColorActiveTitleText = "Bevel.Color.ActiveTitleText";
    public const string ColorInactiveTitleText = "Bevel.Color.InactiveTitleText";
    public const string ColorHighlight = "Bevel.Color.Highlight";
    public const string ColorHighlightText = "Bevel.Color.HighlightText";
    public const string ColorHotTracking = "Bevel.Color.HotTracking";
    public const string ColorInfoWindow = "Bevel.Color.InfoWindow";
    public const string ColorInfoText = "Bevel.Color.InfoText";
    public const string ColorIconFolderBackTop = "Bevel.Color.IconFolderBackTop";
    public const string ColorIconFolderBackBottom = "Bevel.Color.IconFolderBackBottom";
    public const string ColorIconFolderFrontTop = "Bevel.Color.IconFolderFrontTop";
    public const string ColorIconFolderFrontBottom = "Bevel.Color.IconFolderFrontBottom";
    public const string ColorIconFolderEdge = "Bevel.Color.IconFolderEdge";
    public const string ColorIconPaperFillTop = "Bevel.Color.IconPaperFillTop";
    public const string ColorIconPaperFillBottom = "Bevel.Color.IconPaperFillBottom";
    public const string ColorIconPaperEdge = "Bevel.Color.IconPaperEdge";
    public const string ColorIconPaperFold = "Bevel.Color.IconPaperFold";
    public const string ColorIconPaperLine = "Bevel.Color.IconPaperLine";
    public const string ColorIconExeTitle = "Bevel.Color.IconExeTitle";
    public const string ColorIconExeLine = "Bevel.Color.IconExeLine";
    public const string ColorIconSky = "Bevel.Color.IconSky";
    public const string ColorIconSun = "Bevel.Color.IconSun";
    public const string ColorIconMountain = "Bevel.Color.IconMountain";
    public const string ColorIconZipLine = "Bevel.Color.IconZipLine";
    public const string ColorIconZipTeeth = "Bevel.Color.IconZipTeeth";
    public const string ColorIconDriveBody = "Bevel.Color.IconDriveBody";
    public const string ColorIconDriveEdge = "Bevel.Color.IconDriveEdge";
    public const string ColorIconDriveLed = "Bevel.Color.IconDriveLed";
    public const string ColorIconMonitorScreen = "Bevel.Color.IconMonitorScreen";
    public const string ColorIconMonitorInner = "Bevel.Color.IconMonitorInner";
    public const string ColorIconMonitorEdge = "Bevel.Color.IconMonitorEdge";
    public const string ColorIconMonitorStand = "Bevel.Color.IconMonitorStand";
    public const string ColorIconNote = "Bevel.Color.IconNote";
    public const string ColorIconFilmDark = "Bevel.Color.IconFilmDark";
    public const string ColorIconFilmEdge = "Bevel.Color.IconFilmEdge";
    public const string ColorIconFilmFrame = "Bevel.Color.IconFilmFrame";
    public const string ColorIconGlobe = "Bevel.Color.IconGlobe";
    public const string ColorIconGlobeEdge = "Bevel.Color.IconGlobeEdge";
    public const string ColorIconGearBody = "Bevel.Color.IconGearBody";
    public const string ColorIconGearEdge = "Bevel.Color.IconGearEdge";
    public const string ColorIconConsoleBg = "Bevel.Color.IconConsoleBg";
    public const string ColorIconConsoleTitle = "Bevel.Color.IconConsoleTitle";
    public const string ColorIconFontInk = "Bevel.Color.IconFontInk";
    public const string ColorIconPdfRed = "Bevel.Color.IconPdfRed";
    public const string ColorIconSheetGreen = "Bevel.Color.IconSheetGreen";
    public const string ColorIconSheetGrid = "Bevel.Color.IconSheetGrid";
    public const string ColorIconWordBlue = "Bevel.Color.IconWordBlue";
    public const string ColorIconPptOrange = "Bevel.Color.IconPptOrange";
    public const string ColorIconDbBody = "Bevel.Color.IconDbBody";
    public const string ColorIconDbTop = "Bevel.Color.IconDbTop";
    public const string ColorIconDbEdge = "Bevel.Color.IconDbEdge";
    public const string ColorIconCodeInk = "Bevel.Color.IconCodeInk";
    public const string ColorIconDiscBody = "Bevel.Color.IconDiscBody";
    public const string ColorIconDiscSheen = "Bevel.Color.IconDiscSheen";

    public const string BrushButtonFace = "Bevel.Brush.ButtonFace";
    public const string BrushButtonHighlight = "Bevel.Brush.ButtonHighlight";
    public const string BrushButtonLight = "Bevel.Brush.ButtonLight";
    public const string BrushButtonShadow = "Bevel.Brush.ButtonShadow";
    public const string BrushButtonDkShadow = "Bevel.Brush.ButtonDkShadow";
    public const string BrushWindow = "Bevel.Brush.Window";
    public const string BrushWindowText = "Bevel.Brush.WindowText";
    public const string BrushWindowFrame = "Bevel.Brush.WindowFrame";
    public const string BrushGrayText = "Bevel.Brush.GrayText";
    public const string BrushAppWorkspace = "Bevel.Brush.AppWorkspace";
    public const string BrushDesktop = "Bevel.Brush.Desktop";
    public const string BrushMenu = "Bevel.Brush.Menu";
    public const string BrushMenuText = "Bevel.Brush.MenuText";
    public const string BrushScrollbar = "Bevel.Brush.Scrollbar";
    public const string BrushActiveTitle = "Bevel.Brush.ActiveTitle";
    public const string BrushGradientActiveTitle = "Bevel.Brush.GradientActiveTitle";
    public const string BrushInactiveTitle = "Bevel.Brush.InactiveTitle";
    public const string BrushGradientInactiveTitle = "Bevel.Brush.GradientInactiveTitle";
    public const string BrushActiveTitleText = "Bevel.Brush.ActiveTitleText";
    public const string BrushInactiveTitleText = "Bevel.Brush.InactiveTitleText";
    public const string BrushHighlight = "Bevel.Brush.Highlight";
    public const string BrushHighlightText = "Bevel.Brush.HighlightText";
    public const string BrushHotTracking = "Bevel.Brush.HotTracking";
    public const string BrushInfoWindow = "Bevel.Brush.InfoWindow";
    public const string BrushInfoText = "Bevel.Brush.InfoText";
    public const string BrushIconFolderBackTop = "Bevel.Brush.IconFolderBackTop";
    public const string BrushIconFolderBackBottom = "Bevel.Brush.IconFolderBackBottom";
    public const string BrushIconFolderFrontTop = "Bevel.Brush.IconFolderFrontTop";
    public const string BrushIconFolderFrontBottom = "Bevel.Brush.IconFolderFrontBottom";
    public const string BrushIconFolderEdge = "Bevel.Brush.IconFolderEdge";
    public const string BrushIconPaperFillTop = "Bevel.Brush.IconPaperFillTop";
    public const string BrushIconPaperFillBottom = "Bevel.Brush.IconPaperFillBottom";
    public const string BrushIconPaperEdge = "Bevel.Brush.IconPaperEdge";
    public const string BrushIconPaperFold = "Bevel.Brush.IconPaperFold";
    public const string BrushIconPaperLine = "Bevel.Brush.IconPaperLine";
    public const string BrushIconExeTitle = "Bevel.Brush.IconExeTitle";
    public const string BrushIconExeLine = "Bevel.Brush.IconExeLine";
    public const string BrushIconSky = "Bevel.Brush.IconSky";
    public const string BrushIconSun = "Bevel.Brush.IconSun";
    public const string BrushIconMountain = "Bevel.Brush.IconMountain";
    public const string BrushIconZipLine = "Bevel.Brush.IconZipLine";
    public const string BrushIconZipTeeth = "Bevel.Brush.IconZipTeeth";
    public const string BrushIconDriveBody = "Bevel.Brush.IconDriveBody";
    public const string BrushIconDriveEdge = "Bevel.Brush.IconDriveEdge";
    public const string BrushIconDriveLed = "Bevel.Brush.IconDriveLed";
    public const string BrushIconMonitorScreen = "Bevel.Brush.IconMonitorScreen";
    public const string BrushIconMonitorInner = "Bevel.Brush.IconMonitorInner";
    public const string BrushIconMonitorEdge = "Bevel.Brush.IconMonitorEdge";
    public const string BrushIconMonitorStand = "Bevel.Brush.IconMonitorStand";
    public const string BrushIconNote = "Bevel.Brush.IconNote";
    public const string BrushIconFilmDark = "Bevel.Brush.IconFilmDark";
    public const string BrushIconFilmEdge = "Bevel.Brush.IconFilmEdge";
    public const string BrushIconFilmFrame = "Bevel.Brush.IconFilmFrame";
    public const string BrushIconGlobe = "Bevel.Brush.IconGlobe";
    public const string BrushIconGlobeEdge = "Bevel.Brush.IconGlobeEdge";
    public const string BrushIconGearBody = "Bevel.Brush.IconGearBody";
    public const string BrushIconGearEdge = "Bevel.Brush.IconGearEdge";
    public const string BrushIconConsoleBg = "Bevel.Brush.IconConsoleBg";
    public const string BrushIconConsoleTitle = "Bevel.Brush.IconConsoleTitle";
    public const string BrushIconFontInk = "Bevel.Brush.IconFontInk";
    public const string BrushIconPdfRed = "Bevel.Brush.IconPdfRed";
    public const string BrushIconSheetGreen = "Bevel.Brush.IconSheetGreen";
    public const string BrushIconSheetGrid = "Bevel.Brush.IconSheetGrid";
    public const string BrushIconWordBlue = "Bevel.Brush.IconWordBlue";
    public const string BrushIconPptOrange = "Bevel.Brush.IconPptOrange";
    public const string BrushIconDbBody = "Bevel.Brush.IconDbBody";
    public const string BrushIconDbTop = "Bevel.Brush.IconDbTop";
    public const string BrushIconDbEdge = "Bevel.Brush.IconDbEdge";
    public const string BrushIconCodeInk = "Bevel.Brush.IconCodeInk";
    public const string BrushIconDiscBody = "Bevel.Brush.IconDiscBody";
    public const string BrushIconDiscSheen = "Bevel.Brush.IconDiscSheen";

    public const string MetricCaptionHeight = "Bevel.Metric.CaptionHeight";
    public const string MetricCaptionButtonWidth = "Bevel.Metric.CaptionButtonWidth";
    public const string MetricCaptionButtonHeight = "Bevel.Metric.CaptionButtonHeight";
    public const string MetricResizeBorder = "Bevel.Metric.ResizeBorder";
    public const string MetricEdgeThickness = "Bevel.Metric.EdgeThickness";
    public const string MetricScrollBarSize = "Bevel.Metric.ScrollBarSize";
    public const string MetricMenuBarHeight = "Bevel.Metric.MenuBarHeight";
    public const string MetricMenuItemHeight = "Bevel.Metric.MenuItemHeight";
    public const string MetricTaskbarHeight = "Bevel.Metric.TaskbarHeight";
    public const string MetricIconGridCellWidth = "Bevel.Metric.IconGridCellWidth";
    public const string MetricIconGridCellHeight = "Bevel.Metric.IconGridCellHeight";
    public const string MetricFocusRectInset = "Bevel.Metric.FocusRectInset";
    public const string MetricCornerRadius = "Bevel.Metric.CornerRadius";
    public const string MetricButtonPadding = "Bevel.Metric.ButtonPadding";
    public const string MetricWindowContentBorder = "Bevel.Metric.WindowContentBorder";
    public const string MetricWindowContentInset = "Bevel.Metric.WindowContentInset";
    public const string MetricCaptionMargin = "Bevel.Metric.CaptionMargin";
    public const string MetricCaptionPadding = "Bevel.Metric.CaptionPadding";

    public const string FontUI = "Bevel.Font.UI";
    public const string FontCaption = "Bevel.Font.Caption";
    public const string FontMono = "Bevel.Font.Mono";

    public const string EdgeRendering = "Bevel.Edge.Rendering";
}
